

- Error 1 - wrong password
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)")

- Error 2 - wrong db name declared
Traceback (most recent call last):
  File "server.py", line 6, in <module>
    mysql = MySQLConnector(app, 'mydb')
  File "/Users/alfredgarcia/codingdojo/codingdojo/python/week4/flask_mysql/mysqlconnection.py", line 40, in MySQLConnector
    return MySQLConnection(app, db)
  File "/Users/alfredgarcia/codingdojo/codingdojo/python/week4/flask_mysql/mysqlconnection.py", line 9, in __init__
    'database': mydb, # we got db as an argument
NameError: global name 'mydb' is not defined

- Error 3 - wrong port number
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (2003, "Can't connect to MySQL server on '127.0.0.1' (61)")

- Error 4 - wrong user
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'agarcia'@'localhost' (using password: YES)")
